# Generated by Django 6.0.5 on 2026-07-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'COD'), ('UPI', 'UPI'), ('CARD', 'CARD'), ('NET_BANKING', 'NET_BANKING'), ('RAZORPAY', 'RAZORPAY')], max_length=30),
        ),
    ]
