# Generated by Django 6.0.5 on 2026-07-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tagLine', models.CharField(max_length=100)),
                ('matter', models.CharField(max_length=1000)),
                ('OfferType', models.CharField(choices=[('add', 'Add'), ('sell', 'Sell'), ('anoucement', 'Anouncement')], default=None, max_length=50)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('offerBannerStatus', models.CharField(choices=[('active', 'Active'), ('deactive', 'Deactive')], default='deactive', max_length=80)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
