# Generated by Django 6.0.5 on 2026-08-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_email_alter_customuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('seller', 'Seller'), ('delivery_partner', 'Delivery Partner'), ('marketing', 'Marketing'), ('product_reviewer', 'Product Reviewer')], default='user', max_length=30),
        ),
    ]
