# Generated by Django 6.0.5 on 2026-07-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_cartitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
