# Generated by Django 5.2 on 2026-07-03 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_ordered_at_order_created_at_and_more'),
        ('seller', '0002_alter_product_id_alter_productimage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seller.productvariant'),
        ),
    ]
