# Generated by Django 6.0.5 on 2026-07-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_id_alter_orderitem_id_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('INITIATED', 'Refund Initiated'), ('PROCESSING', 'Refund Processing'), ('SUCCESS', 'Refund Completed'), ('FAILED', 'Refund Failed')], default='NOT_REQUIRED', max_length=30),
        ),
    ]
