# Generated by Django 6.0.5 on 2026-07-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_buy_now',
            field=models.BooleanField(default=False),
        ),
    ]
